apiVersion: v1
kind: Service
metadata:
  name: openvas-service
spec:
  selector:
    app: openvas-scanner  # 这里应该匹配你Pod的标签
  ports:
    - protocol: TCP
      port: 80  # 服务监听的端口
      targetPort: 80  # Pod内部应用监听的端口
  type: NodePort  # 或者 "ClusterIP", "LoadBalancer" 等