apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa # 提供访问集群pod的能力
      containers:
      - name: autoscaler
        image: cloudnative-vt/autoscaler:v1.0
        env:
        - name: SCANNER_NAMESPACE
          value: "vt-scanner"
        - name: PROMETHEUS_HOST
          value: prometheus-server.monitoring.svc.cluster.local
        - name: PROMETHEUS_PORT
          value: "80"
        - name: TASK_MANAGER_HOST
          value: task-manager.default.svc.cluster.local
        - name: TASK_MANAGER_PORT
          value: "80"
        - name: RESOURCE_MANAGER_HOST
          value: resource-manager.default.svc.cluster.local
        - name: RESOURCE_MANAGER_PORT
          value: "80"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # 如果需要设置环境变量或挂载卷，请在这里添加相应配置
