apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvas-scaler-deployment
  labels:
    app: openvas-scaler
spec:
  replicas: 1 # 运行的应用程序实例数量
  selector:
    matchLabels:
      app: openvas-scaler
  template:
    metadata:
      labels:
        app: openvas-scaler
    spec:
      containers:
      - name: openvas-scaler
        image: cloudnative-vt/openvas-scaler:v1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openvas-scaler-service
spec:
  selector:
    app: openvas-scaler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort # 根据你的需求选择合适的类型