apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvas-autoscaler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: openvas-autoscaler-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openvas-autoscaler-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: openvas-autoscaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: openvas-autoscaler-role
  apiGroup: rbac.authorization.k8s.io