apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-manager-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: resource-manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-manager-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: resource-manager-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-manager-role
  apiGroup: rbac.authorization.k8s.io