apiVersion: v1
kind: Pod
metadata:
  name: zap   # 这里会在扩容时自动替换名称, 防止pod名称出现重复
  namespace: vtscanner  # 注意: 有且只有扫描器要在vtsanner命名空间下
  labels:
    app: vtscan
    type: scanner
    engine: zap
spec:
  containers:
  - name: zap-container
    image: ghcr.io/zaproxy/zaproxy:stable
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8090  # ZAP默认API端口
    env:
      - name: OWASP_ZAP_API_KEY
        value: "cstclolud"  # 设置API密钥
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8090", "-config", "api.key=cstclolud"]
