apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-scaler-deployment
  labels:
    app: zap-scaler
spec:
  replicas: 1 # 运行的应用程序实例数量
  selector:
    matchLabels:
      app: zap-scaler
  template:
    metadata:
      labels:
        app: zap-scaler
    spec:
      containers:
      - name: zap-scaler
        image: cloudnative-vt/zap-scaler:v1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zap-scaler-service
spec:
  selector:
    app: zap-scaler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort # 根据你的需求选择合适的类型