apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager-scheduler
  template:
    metadata:
      labels:
        app: resource-manager-scheduler
    spec:
      serviceAccountName: resource-manager-sa # 提供访问集群pod的能力
      containers:
      - name: resource-manager-scheduler
        image: cloudnative-vt/resource-manager-scheduler:latest
        env:
        - name: DELETE_WAIT_TIME   # 删除等待时间，秒为单位
          value: "600"  
        - name: TASK_MANAGER_HOST
          value: task-manager.default.svc.cluster.local
        - name: TASK_MANAGER_PORT
          value: "80"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # 如果需要设置环境变量或挂载卷，请在这里添加相应配置
