apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager-api-deployment
  labels:
    app: resource-manager-api
spec:
  replicas: 1 # 运行的应用程序实例数量
  selector:
    matchLabels:
      app: resource-manager-api
  template:
    metadata:
      labels:
        app: resource-manager-api
    spec:
      containers:
      - name: resource-manager-api
        image: cloudnative-vt/resource-manager-api:v1.0
        ports:
        - containerPort: 80
        env:
        - name: RESOURCE_manager_PORT
          value: "80"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: resource-manager-api-service
spec:
  selector:
    app: resource-manager-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort # 根据你的需求选择合适的类型